import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  Plus,
  Search,
  Lock,
  ArrowRight,
  Download,
  Copy,
  Trash2,
  ShieldCheck,
  AlertTriangle,
  FolderKanban,
  Target,
  ExternalLink,
  Layers,
  GraduationCap,
  Building2,
  Briefcase,
  Store,
  UserCheck,
  CheckCircle2,
} from 'lucide-react';
import { AudienceShifterProject, ProductIdea } from '../../types/brand';
import { useAuth } from '../../context/AuthContext';
import {
  getSavedProjects,
  deleteProjectFromStorage,
  duplicateProjectInStorage,
  saveProjectToStorage,
} from '../../services/projectStorage';
import { AVAILABLE_AUDIENCES } from '../../services/brandGenerator';

interface DashboardScreenProps {
  onOpenProject: (project: AudienceShifterProject) => void;
  onNewProject: () => void;
  onSelectPreset: (preset: ProductIdea) => void;
}

export const DashboardScreen: React.FC<DashboardScreenProps> = ({
  onOpenProject,
  onNewProject,
  onSelectPreset,
}) => {
  const { user, isAuthenticated, openAuthModal, showToast } = useAuth();
  const [projects, setProjects] = useState<AudienceShifterProject[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterMode, setFilterMode] = useState<'all' | 'locked' | 'alerts'>('all');
  const [deletingId, setDeletingId] = useState<string | null>(null);

  useEffect(() => {
    setProjects(getSavedProjects());
  }, []);

  const handleDelete = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const updated = deleteProjectFromStorage(id);
    setProjects(updated);
    setDeletingId(null);
    showToast('Project deleted successfully', 'info');
  };

  const handleDuplicate = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const cloned = duplicateProjectInStorage(id);
    if (cloned) {
      setProjects(getSavedProjects());
      showToast(`Duplicated as "${cloned.title}"`);
    }
  };

  const handleExportMarkdown = (project: AudienceShifterProject, e: React.MouseEvent) => {
    e.stopPropagation();
    const audiencesText = Object.values(project.audienceShifts)
      .map(
        (shift) => `
### Audience: ${shift.audienceName}
- **Positioning**: ${shift.positioning}
- **Tone of Voice**: ${shift.toneOfVoice}
- **Key Motivation**: ${shift.keyMotivation}
- **Tagline**: "${shift.tagline}"
- **Headline**: "${shift.exampleHeadline}"
- **Key Message**: "${shift.exampleMessage}"
- **Call to Action**: "${shift.callToAction}"
`
      )
      .join('\n---\n');

    const markdownContent = `# NO BUGS Brand Kit: ${project.title}
*Generated by NO BUGS Audience Shifter*
*Last updated: ${new Date(project.updatedAt).toLocaleDateString()}*

## 1. Core Problem & Promise
- **Original Problem**: ${project.understanding.coreProblem}
- **Product Purpose**: ${project.understanding.productPurpose}
- **Product Promise**: ${project.understanding.productPromise}

## 2. Locked Core Value (Non-Negotiable Anchor)
> **"${project.coreValueLock.coreValue}"**
*Lock Status*: ${project.coreValueLock.isLocked ? 'LOCKED (Zero Value Drift Enforced)' : 'Flexible'}

## 3. Adapted Audience Brand Expressions
${audiencesText}

## 4. Integrity & Consistency Report
- **Overall Score**: ${project.consistency.overallScore}%
- **Core Value Preserved**: ${project.consistency.coreValuePreserved ? 'YES' : 'NO'}
- **Product Identity Preserved**: ${project.consistency.productIdentityPreserved ? 'YES' : 'NO'}
`;

    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${project.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-brand-kit.md`;
    link.click();
    URL.revokeObjectURL(url);
    showToast('Brand Kit downloaded (.md)');
  };

  // Filter projects
  const filteredProjects = projects.filter((p) => {
    const matchesSearch =
      p.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.coreValueLock.coreValue.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (p.product.industry || '').toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.understanding.coreProblem.toLowerCase().includes(searchQuery.toLowerCase());

    if (!matchesSearch) return false;

    if (filterMode === 'locked') {
      return p.coreValueLock.isLocked;
    }
    if (filterMode === 'alerts') {
      return p.consistency.valueDriftAlerts.length > 0;
    }
    return true;
  });

  // Calculate Metrics
  const totalProjects = projects.length;
  const lockedProjects = projects.filter((p) => p.coreValueLock.isLocked).length;
  const totalAudiencesShifted = projects.reduce(
    (acc, curr) => acc + (curr.selectedAudiences?.length || 0),
    0
  );
  const avgIntegrity =
    projects.length > 0
      ? Math.round(
          projects.reduce((acc, curr) => acc + (curr.consistency?.overallScore || 100), 0) /
            projects.length
        )
      : 100;

  // Helper for Audience Icon
  const getAudienceLabel = (audId: string) => {
    const found = AVAILABLE_AUDIENCES.find((a) => a.id === audId);
    return found ? found.shortLabel : audId;
  };

  const getAudienceIcon = (audId: string) => {
    switch (audId) {
      case 'students':
        return <GraduationCap className="w-3 h-3 text-[#FF6124]" />;
      case 'parents':
        return <ShieldCheck className="w-3 h-3 text-emerald-600 dark:text-emerald-400" />;
      case 'institutions':
        return <Building2 className="w-3 h-3 text-indigo-600 dark:text-indigo-400" />;
      case 'enterprise':
        return <Briefcase className="w-3 h-3 text-sky-600 dark:text-sky-400" />;
      case 'smallbiz':
        return <Store className="w-3 h-3 text-amber-600 dark:text-amber-400" />;
      default:
        return <UserCheck className="w-3 h-3 text-purple-600 dark:text-purple-400" />;
    }
  };

  // 1. Enforce that Dashboard is available ONLY after sign in
  if (!isAuthenticated) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-16 sm:py-24 text-center space-y-8 animate-in fade-in duration-200">
        <div className="w-16 h-16 mx-auto rounded-3xl bg-[#FF6124]/10 dark:bg-[#FF6124]/20 border border-[#FF6124]/30 flex items-center justify-center text-[#FF6124] shadow-sm">
          <Lock className="w-8 h-8 stroke-[2.5]" />
        </div>

        <div className="space-y-3">
          <span className="text-xs font-mono uppercase tracking-widest text-[#FF6124] font-bold">
            Private Founder Workspace
          </span>
          <h1 className="text-3xl sm:text-4xl font-black text-neutral-900 dark:text-neutral-50 tracking-tight">
            Sign In to Access Dashboard
          </h1>
          <p className="text-sm text-neutral-600 dark:text-neutral-400 max-w-md mx-auto leading-relaxed">
            The dashboard is available only after signing in. Access your saved brand models, locked core values, and multi-market audience adaptations securely.
          </p>
        </div>

        <div className="p-6 rounded-2xl bg-white dark:bg-[#1c1c1c] border border-[#E4DFD3] dark:border-[#2a2a2a] shadow-md max-w-sm mx-auto space-y-3">
          <button
            type="button"
            onClick={() => openAuthModal('signin')}
            className="w-full py-3 px-4 rounded-xl bg-[#FF6124] hover:bg-[#e5531b] active:bg-[#d64a15] text-white text-sm font-bold flex items-center justify-center gap-2 shadow-xs transition-colors cursor-pointer"
          >
            <span>Sign In to Continue</span>
            <ArrowRight className="w-4 h-4" />
          </button>

          <button
            type="button"
            onClick={() => openAuthModal('signup')}
            className="w-full py-2.5 px-4 rounded-xl border border-[#D8D2C5] dark:border-[#333] hover:bg-neutral-50 dark:hover:bg-[#252525] text-neutral-800 dark:text-neutral-200 text-xs font-bold transition-colors cursor-pointer"
          >
            Create Free Account
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8 sm:py-12 space-y-8 animate-in fade-in duration-200">
      {/* Top Banner & User Greeting */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[#E4DFD3] dark:border-[#2a2a2a] pb-6">
        <div>
          <div className="flex items-center gap-2.5">
            <span className="p-1.5 rounded-lg bg-[#FF6124]/10 dark:bg-[#FF6124]/20 text-[#FF6124]">
              <FolderKanban className="w-5 h-5" />
            </span>
            <h1 className="text-2xl sm:text-3xl font-black tracking-tight text-neutral-900 dark:text-neutral-50">
              Founder Dashboard
            </h1>
          </div>
          <p className="text-xs sm:text-sm text-neutral-600 dark:text-neutral-400 mt-1">
            {isAuthenticated
              ? `Welcome back, ${user?.name}. Here are your saved brand projects and audience adaptations.`
              : 'Inspect your active projects, explore audience shifts, and manage multi-market positioning.'}
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            type="button"
            onClick={onNewProject}
            className="px-4 py-2.5 rounded-xl bg-[#FF6124] hover:bg-[#e5531b] active:bg-[#d64a15] text-white text-xs sm:text-sm font-bold flex items-center gap-2 shadow-xs transition-colors cursor-pointer"
          >
            <Plus className="w-4 h-4 stroke-[3]" />
            <span>New Brand Shift</span>
          </button>
        </div>
      </div>

      {/* Metrics Row */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="p-4 rounded-2xl bg-white dark:bg-[#1c1c1c] border border-[#E4DFD3] dark:border-[#2a2a2a] shadow-2xs">
          <div className="flex items-center justify-between text-neutral-500 dark:text-neutral-400">
            <span className="text-xs font-semibold uppercase tracking-wider">Total Projects</span>
            <FolderKanban className="w-4 h-4 text-neutral-400" />
          </div>
          <div className="mt-2 text-2xl sm:text-3xl font-black text-neutral-900 dark:text-neutral-50 tabular-nums">
            {totalProjects}
          </div>
          <span className="text-[11px] text-neutral-500 dark:text-neutral-400 mt-1 block">
            Saved brand models in workspace
          </span>
        </div>

        <div className="p-4 rounded-2xl bg-white dark:bg-[#1c1c1c] border border-[#E4DFD3] dark:border-[#2a2a2a] shadow-2xs">
          <div className="flex items-center justify-between text-neutral-500 dark:text-neutral-400">
            <span className="text-xs font-semibold uppercase tracking-wider">Audiences Shifted</span>
            <Target className="w-4 h-4 text-[#FF6124]" />
          </div>
          <div className="mt-2 text-2xl sm:text-3xl font-black text-[#FF6124] tabular-nums">
            {totalAudiencesShifted}
          </div>
          <span className="text-[11px] text-neutral-500 dark:text-neutral-400 mt-1 block">
            Target segments communicated to
          </span>
        </div>

        <div className="p-4 rounded-2xl bg-white dark:bg-[#1c1c1c] border border-[#E4DFD3] dark:border-[#2a2a2a] shadow-2xs">
          <div className="flex items-center justify-between text-neutral-500 dark:text-neutral-400">
            <span className="text-xs font-semibold uppercase tracking-wider">Core Invariants</span>
            <Lock className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
          </div>
          <div className="mt-2 text-2xl sm:text-3xl font-black text-emerald-700 dark:text-emerald-400 tabular-nums">
            {lockedProjects} / {totalProjects}
          </div>
          <span className="text-[11px] text-neutral-500 dark:text-neutral-400 mt-1 block">
            Values anchored with zero drift
          </span>
        </div>

        <div className="p-4 rounded-2xl bg-white dark:bg-[#1c1c1c] border border-[#E4DFD3] dark:border-[#2a2a2a] shadow-2xs">
          <div className="flex items-center justify-between text-neutral-500 dark:text-neutral-400">
            <span className="text-xs font-semibold uppercase tracking-wider">Avg Integrity Score</span>
            <ShieldCheck className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
          </div>
          <div className="mt-2 text-2xl sm:text-3xl font-black text-neutral-900 dark:text-neutral-50 tabular-nums">
            {avgIntegrity}%
          </div>
          <span className="text-[11px] text-emerald-600 dark:text-emerald-400 font-semibold mt-1 flex items-center gap-1">
            <CheckCircle2 className="w-3 h-3" /> Zero brand hallucination
          </span>
        </div>
      </div>

      {/* Filter & Search Bar */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 bg-white dark:bg-[#1c1c1c] p-3 rounded-2xl border border-[#E4DFD3] dark:border-[#2a2a2a] shadow-2xs">
        {/* Search */}
        <div className="relative flex-1">
          <Search className="w-4 h-4 absolute left-3.5 top-3 text-neutral-400" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search projects, locked core values, or industries..."
            className="w-full pl-9 pr-4 py-2 rounded-xl text-xs sm:text-sm bg-[#FAF8F3] dark:bg-[#121212] border border-[#E4DFD3] dark:border-[#2a2a2a] text-neutral-900 dark:text-neutral-100 placeholder:text-neutral-400 focus:outline-none focus:border-[#FF6124] focus:ring-1 focus:ring-[#FF6124] transition-all"
          />
        </div>

        {/* Filter Pills */}
        <div className="flex items-center gap-1.5 self-start sm:self-auto overflow-x-auto text-xs">
          <button
            type="button"
            onClick={() => setFilterMode('all')}
            className={`px-3 py-1.5 rounded-lg font-semibold transition-colors cursor-pointer ${
              filterMode === 'all'
                ? 'bg-[#FF6124] text-white shadow-2xs'
                : 'text-neutral-600 dark:text-neutral-400 hover:bg-[#F1EEE4] dark:hover:bg-[#252525]'
            }`}
          >
            All ({projects.length})
          </button>
          <button
            type="button"
            onClick={() => setFilterMode('locked')}
            className={`px-3 py-1.5 rounded-lg font-semibold transition-colors cursor-pointer flex items-center gap-1.5 ${
              filterMode === 'locked'
                ? 'bg-[#FF6124] text-white shadow-2xs'
                : 'text-neutral-600 dark:text-neutral-400 hover:bg-[#F1EEE4] dark:hover:bg-[#252525]'
            }`}
          >
            <Lock className="w-3 h-3" />
            <span>Locked Only</span>
          </button>
          <button
            type="button"
            onClick={() => setFilterMode('alerts')}
            className={`px-3 py-1.5 rounded-lg font-semibold transition-colors cursor-pointer flex items-center gap-1.5 ${
              filterMode === 'alerts'
                ? 'bg-[#FF6124] text-white shadow-2xs'
                : 'text-neutral-600 dark:text-neutral-400 hover:bg-[#F1EEE4] dark:hover:bg-[#252525]'
            }`}
          >
            <AlertTriangle className="w-3 h-3" />
            <span>Audited Alerts</span>
          </button>
        </div>
      </div>

      {/* Projects Grid */}
      {filteredProjects.length === 0 ? (
        <div className="text-center py-12 px-4 rounded-2xl bg-white dark:bg-[#1c1c1c] border border-dashed border-[#D8D2C5] dark:border-[#2a2a2a] space-y-3">
          <FolderKanban className="w-8 h-8 mx-auto text-neutral-400" />
          <h3 className="text-base font-bold text-neutral-800 dark:text-neutral-200">
            No projects found matching your query
          </h3>
          <p className="text-xs text-neutral-500 dark:text-neutral-400 max-w-sm mx-auto">
            Try adjusting your search query or start a brand new audience shift for your product.
          </p>
          <button
            type="button"
            onClick={onNewProject}
            className="px-4 py-2 rounded-xl bg-[#FF6124] text-white text-xs font-bold hover:bg-[#e5531b] transition-colors inline-flex items-center gap-2 cursor-pointer mt-2"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Start Brand Shift</span>
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
          {filteredProjects.map((proj) => {
            const isDeleting = deletingId === proj.id;
            return (
              <div
                key={proj.id}
                onClick={() => onOpenProject(proj)}
                className="group relative rounded-2xl bg-white dark:bg-[#1c1c1c] border border-[#E4DFD3] dark:border-[#2a2a2a] hover:border-[#FF6124]/70 dark:hover:border-[#FF6124]/70 p-5 sm:p-6 transition-all shadow-2xs hover:shadow-md cursor-pointer flex flex-col justify-between"
              >
                <div>
                  {/* Top line badges & date */}
                  <div className="flex items-center justify-between gap-2 mb-3">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="text-[10px] font-mono uppercase tracking-wider px-2 py-0.5 rounded-md bg-[#FAF8F3] dark:bg-[#252525] border border-[#E4DFD3] dark:border-[#333] text-neutral-700 dark:text-neutral-300 font-semibold">
                        {proj.product.industry || 'Multi-Audience'}
                      </span>
                      {proj.coreValueLock.isLocked ? (
                        <span className="text-[10px] font-bold px-2 py-0.5 rounded-md bg-emerald-50 dark:bg-emerald-950/60 border border-emerald-200 dark:border-emerald-800/60 text-emerald-800 dark:text-emerald-300 flex items-center gap-1">
                          <Lock className="w-2.5 h-2.5" /> Locked Core
                        </span>
                      ) : (
                        <span className="text-[10px] font-semibold px-2 py-0.5 rounded-md bg-amber-50 dark:bg-amber-950/50 border border-amber-200 dark:border-amber-800/50 text-amber-800 dark:text-amber-300">
                          Draft Value
                        </span>
                      )}
                    </div>

                    <span className="text-[11px] text-neutral-400 dark:text-neutral-500 tabular-nums">
                      {new Date(proj.updatedAt).toLocaleDateString(undefined, {
                        month: 'short',
                        day: 'numeric',
                      })}
                    </span>
                  </div>

                  {/* Project Title */}
                  <h3 className="text-base sm:text-lg font-black text-neutral-900 dark:text-neutral-50 group-hover:text-[#FF6124] transition-colors leading-tight">
                    {proj.title}
                  </h3>

                  {/* Product description preview */}
                  <p className="text-xs text-neutral-600 dark:text-neutral-400 line-clamp-2 mt-1.5 leading-relaxed">
                    {proj.product.rawIdea}
                  </p>

                  {/* Locked Core Invariant callout */}
                  <div className="mt-4 p-3 rounded-xl bg-[#FAF8F3] dark:bg-[#161616] border border-[#EAE5D9] dark:border-[#262626]">
                    <div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-neutral-500 dark:text-neutral-400 mb-1">
                      <Lock className="w-3 h-3 text-[#FF6124]" />
                      <span>The Anchored Invariant</span>
                    </div>
                    <p className="text-xs font-semibold text-neutral-900 dark:text-neutral-100 italic line-clamp-2">
                      "{proj.coreValueLock.coreValue}"
                    </p>
                  </div>

                  {/* Adapted Audiences tags */}
                  <div className="mt-4 space-y-1.5">
                    <span className="text-[11px] font-semibold text-neutral-500 dark:text-neutral-400">
                      Adapted Audiences ({proj.selectedAudiences?.length || 0}):
                    </span>
                    <div className="flex flex-wrap items-center gap-1.5">
                      {proj.selectedAudiences?.map((audId) => (
                        <span
                          key={audId}
                          className="text-xs font-medium px-2.5 py-1 rounded-lg bg-white dark:bg-[#202020] border border-[#E4DFD3] dark:border-[#303030] text-neutral-800 dark:text-neutral-200 flex items-center gap-1.5 shadow-2xs"
                        >
                          {getAudienceIcon(audId)}
                          <span>{getAudienceLabel(audId)}</span>
                        </span>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Bottom Action Footer */}
                <div className="mt-6 pt-4 border-t border-[#E4DFD3] dark:border-[#2a2a2a] flex items-center justify-between gap-2">
                  <div className="flex items-center gap-1">
                    <button
                      type="button"
                      onClick={(e) => handleExportMarkdown(proj, e)}
                      title="Download Markdown Brand Kit"
                      className="p-1.5 rounded-lg text-neutral-500 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-white hover:bg-[#F1EEE4] dark:hover:bg-[#282828] transition-colors cursor-pointer"
                    >
                      <Download className="w-4 h-4" />
                    </button>
                    <button
                      type="button"
                      onClick={(e) => handleDuplicate(proj.id, e)}
                      title="Duplicate project"
                      className="p-1.5 rounded-lg text-neutral-500 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-white hover:bg-[#F1EEE4] dark:hover:bg-[#282828] transition-colors cursor-pointer"
                    >
                      <Copy className="w-4 h-4" />
                    </button>

                    {/* Delete Confirmation */}
                    {isDeleting ? (
                      <div className="flex items-center gap-1 bg-red-50 dark:bg-red-950/50 p-1 rounded-lg border border-red-200 dark:border-red-900/60">
                        <span className="text-[10px] text-red-700 dark:text-red-300 font-bold px-1">
                          Delete?
                        </span>
                        <button
                          type="button"
                          onClick={(e) => handleDelete(proj.id, e)}
                          className="px-2 py-0.5 rounded bg-red-600 hover:bg-red-700 text-white text-[10px] font-bold cursor-pointer"
                        >
                          Yes
                        </button>
                        <button
                          type="button"
                          onClick={(e) => {
                            e.stopPropagation();
                            setDeletingId(null);
                          }}
                          className="px-1.5 py-0.5 text-neutral-500 text-[10px] hover:text-neutral-800 dark:hover:text-neutral-200 cursor-pointer"
                        >
                          Cancel
                        </button>
                      </div>
                    ) : (
                      <button
                        type="button"
                        onClick={(e) => {
                          e.stopPropagation();
                          setDeletingId(proj.id);
                        }}
                        title="Delete project"
                        className="p-1.5 rounded-lg text-neutral-400 hover:text-red-600 dark:hover:text-red-400 hover:bg-red-50 dark:hover:bg-red-950/40 transition-colors cursor-pointer"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    )}
                  </div>

                  <div className="flex items-center gap-1.5 text-xs font-bold text-[#FF6124] group-hover:translate-x-0.5 transition-transform">
                    <span>Open Kit</span>
                    <ArrowRight className="w-4 h-4" />
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Benchmark Templates Section */}
      <div className="mt-12 pt-8 border-t border-[#E4DFD3] dark:border-[#2a2a2a] space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-base sm:text-lg font-bold text-neutral-900 dark:text-neutral-100 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-[#FF6124]" />
              <span>Or Start from a Battle-Tested Preset</span>
            </h2>
            <p className="text-xs text-neutral-500 dark:text-neutral-400">
              One-click templates demonstrating how to shift without altering the core value proposition.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3.5">
          <button
            type="button"
            onClick={() =>
              onSelectPreset({
                title: 'Stripe for Carbon Offsets',
                rawIdea:
                  'A single developer API that calculates logistics freight emissions and automatically buys verified carbon credits.',
                industry: 'Climate Tech / FinTech',
                targetAudience: 'Software Developers & Enterprise Procurement Leads',
                problemSolved: 'Complex carbon accounting audits slowing down supply chains.',
              })
            }
            className="text-left p-3.5 rounded-xl bg-white dark:bg-[#1c1c1c] border border-[#E4DFD3] dark:border-[#2a2a2a] hover:border-[#FF6124] dark:hover:border-[#FF6124] transition-all shadow-2xs group cursor-pointer"
          >
            <div className="text-[10px] font-mono text-[#FF6124] font-bold uppercase">
              API · Climate Tech
            </div>
            <div className="font-bold text-neutral-900 dark:text-neutral-100 text-xs sm:text-sm mt-1 group-hover:text-[#FF6124] transition-colors">
              Stripe for Carbon Offsets
            </div>
            <p className="text-[11px] text-neutral-500 dark:text-neutral-400 mt-1 line-clamp-2">
              Shifts cleanly between developers, corporate CFOs, and sustainability auditors.
            </p>
          </button>

          <button
            type="button"
            onClick={() =>
              onSelectPreset({
                title: 'Duolingo for Financial Literacy',
                rawIdea:
                  'Gamified daily 3-minute financial micro-challenges that teach college students investing, credit building, and emergency savings.',
                industry: 'EdTech / Consumer Finance',
                targetAudience: 'Undergrads, Parents, and Campus Deans',
                problemSolved: 'Dry, complex banking jargon causing financial neglect in young adults.',
              })
            }
            className="text-left p-3.5 rounded-xl bg-white dark:bg-[#1c1c1c] border border-[#E4DFD3] dark:border-[#2a2a2a] hover:border-[#FF6124] dark:hover:border-[#FF6124] transition-all shadow-2xs group cursor-pointer"
          >
            <div className="text-[10px] font-mono text-emerald-600 dark:text-emerald-400 font-bold uppercase">
              EdTech · Finance
            </div>
            <div className="font-bold text-neutral-900 dark:text-neutral-100 text-xs sm:text-sm mt-1 group-hover:text-[#FF6124] transition-colors">
              Duolingo for Finance
            </div>
            <p className="text-[11px] text-neutral-500 dark:text-neutral-400 mt-1 line-clamp-2">
              Speaks playfully to Gen Z while presenting accredited retention ROI to universities.
            </p>
          </button>

          <button
            type="button"
            onClick={() =>
              onSelectPreset({
                title: 'Linear for Marketing Teams',
                rawIdea:
                  'High-velocity campaign issue tracker with keyboard-first navigation and automated sprint dependencies for marketing creative teams.',
                industry: 'Productivity / Creative Ops',
                targetAudience: 'Creative Directors, Brand Designers, and CMOs',
                problemSolved: 'Bloated project management tools causing lost creative assets and missed launch dates.',
              })
            }
            className="text-left p-3.5 rounded-xl bg-white dark:bg-[#1c1c1c] border border-[#E4DFD3] dark:border-[#2a2a2a] hover:border-[#FF6124] dark:hover:border-[#FF6124] transition-all shadow-2xs group cursor-pointer"
          >
            <div className="text-[10px] font-mono text-indigo-600 dark:text-indigo-400 font-bold uppercase">
              Productivity · Creative Ops
            </div>
            <div className="font-bold text-neutral-900 dark:text-neutral-100 text-xs sm:text-sm mt-1 group-hover:text-[#FF6124] transition-colors">
              Linear for Marketing Teams
            </div>
            <p className="text-[11px] text-neutral-500 dark:text-neutral-400 mt-1 line-clamp-2">
              Emphasizes creative flow for designers, campaign cadence for leads, and ROI for CMOs.
            </p>
          </button>
        </div>
      </div>
    </div>
  );
};
